title: Nikhil J. Babani
logo: /assets/images/me.jpeg
description: [![Email](https://img.icons8.com/color/48/000000/email.png)](mailto:nikhil.babani.20@ucl.ac.uk)
[![GitHub](https://img.icons8.com/material-rounded/48/000000/github.png)](https://github.com/your-username)
[![LinkedIn](https://img.icons8.com/color/48/000000/linkedin.png)](https://www.linkedin.com/in/your-username/)
[![Twitter](https://img.icons8.com/color/48/000000/twitter.png)](https://twitter.com/your-username)
show_downloads: true
theme: jekyll-theme-minimal
