title: Nikhil J. Babani
logo: /assets/images/me.jpeg
description: > "Of course, to a mathematician, all this is irrelevant. It's a beautiful problem, and its solution led to many beautiful ideas. That is its complete justification."
# show_downloads: true
theme: jekyll-theme-minimal
